# --- Început Fișier Nou și Corect FINAL ---
platform :ios, '13.0'

# --- LINIA MAGICĂ (Calea corectă) ---
# Îi spunem lui Ruby unde să găsească uneltele Flutter
require_relative File.join('Flutter', 'podhelper')

ENV['LANG'] = 'en_US.UTF-8'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Acum comanda va fi recunoscută
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
# --- Sfârșit Fișier Nou ---