# Copyright 2014 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ---- LINIA NOASTRĂ IMPORTANTĂ ----
platform :ios, '13.0'
# ------------------------------

ENV['POD_CONFIGURATION'] = 'Debug'

# CocoaPods requires your terminal to be using UTF-8 encoding.
# To learn more, see https://github.com/flutter/flutter/issues/23071.
ENV['LANG'] = 'en_US.UTF-8'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end